### Merge FPL Gameweek 1-38 Stats

In [154]:
import pandas as pd
pd.set_option('display.max_columns', None)
import os

In [155]:
def combine_gameweeks(path, saved_filename):
    data_frames = []

    # Loop untuk membaca setiap file CSV dan menambahkannya ke dalam list
    for file_name in os.listdir(path):
        if file_name.endswith('.csv'):
            file_path = os.path.join(path, file_name)
            try:
                # Mencoba membaca file dengan encoding default (utf-8)
                df = pd.read_csv(file_path)
            except UnicodeDecodeError:
                # Jika gagal, mencoba dengan encoding alternatif (latin1)
                df = pd.read_csv(file_path, encoding='latin1')
            
            # Mendapatkan nomor gameweek dari nama file
            gw_number = int(file_name[2:-4])  # Mengambil angka dari nama file (gw1.csv, gw2.csv, ...)
            
            # Menambahkan kolom 'GW' dengan nilai sesuai nomor gameweek
            df['GW'] = gw_number
            
            data_frames.append(df)

    # Menggabungkan semua DataFrame menjadi satu DataFrame
    combined_df = pd.concat(data_frames, ignore_index=True)
    combined_df.to_csv(f'../../data/processed/gameweek/{saved_filename}.csv', index=False)

#### FPL 2016-17 Gameweek

In [156]:
folder_path = '../../data/raw/2016-17/gws'
combine_gameweeks(folder_path, 'combined_gws_1617')

In [157]:
df = pd.read_csv('../../data/processed/gameweek/combined_gws_1617.csv')

print(df.shape)
print(df.columns)

(23679, 56)
Index(['name', 'assists', 'attempted_passes', 'big_chances_created',
       'big_chances_missed', 'bonus', 'bps', 'clean_sheets',
       'clearances_blocks_interceptions', 'completed_passes', 'creativity',
       'dribbles', 'ea_index', 'element', 'errors_leading_to_goal',
       'errors_leading_to_goal_attempt', 'fixture', 'fouls', 'goals_conceded',
       'goals_scored', 'ict_index', 'id', 'influence', 'key_passes',
       'kickoff_time', 'kickoff_time_formatted', 'loaned_in', 'loaned_out',
       'minutes', 'offside', 'open_play_crosses', 'opponent_team', 'own_goals',
       'penalties_conceded', 'penalties_missed', 'penalties_saved',
       'recoveries', 'red_cards', 'round', 'saves', 'selected', 'tackled',
       'tackles', 'target_missed', 'team_a_score', 'team_h_score', 'threat',
       'total_points', 'transfers_balance', 'transfers_in', 'transfers_out',
       'value', 'was_home', 'winning_goals', 'yellow_cards', 'GW'],
      dtype='object')

In [158]:
df

,name,assists,attempted_passes,big_chances_created,big_chances_missed,bonus,bps,clean_sheets,clearances_blocks_interceptions,completed_passes,creativity,dribbles,ea_index,element,errors_leading_to_goal,errors_leading_to_goal_attempt,fixture,fouls,goals_conceded,goals_scored,ict_index,id,influence,key_passes,kickoff_time,kickoff_time_formatted,loaned_in,loaned_out,minutes,offside,open_play_crosses,opponent_team,own_goals,penalties_conceded,penalties_missed,penalties_saved,recoveries,red_cards,round,saves,selected,tackled,tackles,target_missed,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,winning_goals,yellow_cards,GW
0,Aaron_Cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,454,0,0,10,0,0,0,0.0,454,0.0,0,2016-08-15T19:00:00Z,15 Aug 20:00,0,0,0,0,0,4,0,0,0,0,0,0,1,0,14023,0,0,0,1,2,0.0,0,0,0,0,55,False,0,0,1
1,Aaron_Lennon,0,3,0,0,0,6,0,1,2,0.3,0,0,142,0,0,3,0,0,0,0.9,142,8.2,0,2016-08-13T14:00:00Z,13 Aug 15:00,0,0,15,0,0,17,0,0,0,0,1,0,1,0,13918,1,2,0,1,1,0.0,1,0,0,0,60,True,0,0,1
2,Aaron_Ramsey,0,26,0,0,0,5,0,2,22,4.9,1,0,16,0,0,8,0,3,0,3.0,16,2.2,0,2016-08-14T15:00:00Z,14 Aug 16:00,0,0,60,0,0,9,0,0,0,0,2,0,1,0,163170,2,0,1,4,3,23.0,2,0,0,0,80,True,0,0,1
3,Abdoulaye_Doucouré,0,0,0,0,0,0,0,0,0,0.0,0,0,482,0,0,7,0,0,0,0.0,482,0.0,0,2016-08-13T14:00:00Z,13 Aug 15:00,0,0,0,0,0,13,0,0,0,0,0,0,1,0,1051,0,0,0,1,1,0.0,0,0,0,0,50,False,0,0,1
4,Abdul Rahman_Baba,0,0,0,0,0,0,0,0,0,0.0,0,0,80,0,0,10,0,0,0,0.0,80,0.0,0,2016-08-15T19:00:00Z,15 Aug 20:00,0,0,0,0,0,20,0,0,0,0,0,0,1,0,1243,0,0,0,1,2,0.0,0,0,0,0,55,True,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23674,Yohan_Cabaye,0,65,0,0,3,42,0,5,57,41.2,3,0,118,0,0,86,0,3,1,21.7,4665,58.4,3,2016-10-22T14:00:00Z,22 Oct 15:00,0,0,90,0,0,8,0,0,0,0,7,0,9,0,50415,0,3,2,1,3,117.0,10,-2177,152,2329,56,False,0,0,9
23675,Younes_Kaboul,0,34,0,0,0,23,1,7,28,0.6,0,0,341,0,0,89,2,0,0,2.6,4888,13.8,0,2016-10-22T14:00:00Z,22 Oct 15:00,0,0,90,0,0,16,0,0,0,0,5,0,9,0,23486,1,0,0,0,0,12.0,6,1403,1897,494,44,False,0,0,9
23676,Zlatan_Ibrahimovic,0,40,0,0,0,8,0,4,35,23.1,0,0,272,0,0,84,2,4,0,8.7,4819,7.6,1,2016-10-23T15:00:00Z,23 Oct 16:00,0,0,90,1,0,4,0,0,0,0,3,0,9,0,1615515,1,0,2,0,4,56.0,2,-237262,4227,241489,113,False,0,0,9
23677,Álvaro_Arbeloa,0,0,0,0,0,0,0,0,0,0.0,0,0,568,0,0,90,0,0,0,0.0,5115,0.0,0,2016-10-22T14:00:00Z,22 Oct 15:00,0,0,0,0,0,15,0,0,0,0,0,0,9,0,3162,0,0,0,0,1,0.0,0,-291,140,431,49,True,0,0,9
23678,Álvaro_Negredo,0,25,0,2,0,-3,1,6,12,12.8,0,0,478,0,0,81,1,0,0,12.6,5025,8.6,0,2016-10-22T14:00:00Z,22 Oct 15:00,0,0,90,2,0,1,0,0,0,0,4,0,9,0,613044,3,0,1,0,0,105.0,2,-98062,3386,101448,64,False,0,0,9

In [159]:
df.head(3)

,name,assists,attempted_passes,big_chances_created,big_chances_missed,bonus,bps,clean_sheets,clearances_blocks_interceptions,completed_passes,creativity,dribbles,ea_index,element,errors_leading_to_goal,errors_leading_to_goal_attempt,fixture,fouls,goals_conceded,goals_scored,ict_index,id,influence,key_passes,kickoff_time,kickoff_time_formatted,loaned_in,loaned_out,minutes,offside,open_play_crosses,opponent_team,own_goals,penalties_conceded,penalties_missed,penalties_saved,recoveries,red_cards,round,saves,selected,tackled,tackles,target_missed,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,winning_goals,yellow_cards,GW
0,Aaron_Cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,454,0,0,10,0,0,0,0.0,454,0.0,0,2016-08-15T19:00:00Z,15 Aug 20:00,0,0,0,0,0,4,0,0,0,0,0,0,1,0,14023,0,0,0,1,2,0.0,0,0,0,0,55,False,0,0,1
1,Aaron_Lennon,0,3,0,0,0,6,0,1,2,0.3,0,0,142,0,0,3,0,0,0,0.9,142,8.2,0,2016-08-13T14:00:00Z,13 Aug 15:00,0,0,15,0,0,17,0,0,0,0,1,0,1,0,13918,1,2,0,1,1,0.0,1,0,0,0,60,True,0,0,1
2,Aaron_Ramsey,0,26,0,0,0,5,0,2,22,4.9,1,0,16,0,0,8,0,3,0,3.0,16,2.2,0,2016-08-14T15:00:00Z,14 Aug 16:00,0,0,60,0,0,9,0,0,0,0,2,0,1,0,163170,2,0,1,4,3,23.0,2,0,0,0,80,True,0,0,1

#### FPL 2017-18 Gameweek

In [160]:
folder_path = '../../data/raw/2017-18/gws'
combine_gameweeks(folder_path, 'combined_gws_1718')

In [161]:
df = pd.read_csv('../../data/processed/gameweek/combined_gws_1718.csv')

print(df.shape)
print(df.columns)

(22467, 56)
Index(['name', 'assists', 'attempted_passes', 'big_chances_created',
       'big_chances_missed', 'bonus', 'bps', 'clean_sheets',
       'clearances_blocks_interceptions', 'completed_passes', 'creativity',
       'dribbles', 'ea_index', 'element', 'errors_leading_to_goal',
       'errors_leading_to_goal_attempt', 'fixture', 'fouls', 'goals_conceded',
       'goals_scored', 'ict_index', 'id', 'influence', 'key_passes',
       'kickoff_time', 'kickoff_time_formatted', 'loaned_in', 'loaned_out',
       'minutes', 'offside', 'open_play_crosses', 'opponent_team', 'own_goals',
       'penalties_conceded', 'penalties_missed', 'penalties_saved',
       'recoveries', 'red_cards', 'round', 'saves', 'selected', 'tackled',
       'tackles', 'target_missed', 'team_a_score', 'team_h_score', 'threat',
       'total_points', 'transfers_balance', 'transfers_in', 'transfers_out',
       'value', 'was_home', 'winning_goals', 'yellow_cards', 'GW'],
      dtype='object')

In [162]:
df.head(3)

,name,assists,attempted_passes,big_chances_created,big_chances_missed,bonus,bps,clean_sheets,clearances_blocks_interceptions,completed_passes,creativity,dribbles,ea_index,element,errors_leading_to_goal,errors_leading_to_goal_attempt,fixture,fouls,goals_conceded,goals_scored,ict_index,id,influence,key_passes,kickoff_time,kickoff_time_formatted,loaned_in,loaned_out,minutes,offside,open_play_crosses,opponent_team,own_goals,penalties_conceded,penalties_missed,penalties_saved,recoveries,red_cards,round,saves,selected,tackled,tackles,target_missed,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,winning_goals,yellow_cards,GW
0,Aaron_Cresswell,0,10,0,0,0,3,0,0,9,0.6,0,0,443,0,0,9,0,2,0,1.9,443,0.4,0,2017-08-13T15:00:00Z,13 Aug 16:00,0,0,9,0,0,12,0,0,0,0,0,0,1,0,25136,0,0,0,0,4,18.0,0,0,0,0,50,False,0,0,1
1,Aaron_Lennon,0,0,0,0,0,0,0,0,0,0.0,0,0,153,0,0,5,0,0,0,0.0,153,0.0,0,2017-08-12T14:00:00Z,12 Aug 15:00,0,0,0,0,0,15,0,0,0,0,0,0,1,0,4681,0,0,0,0,1,0.0,0,0,0,0,55,True,0,0,1
2,Aaron_Mooy,1,52,0,0,0,22,1,5,41,46.9,0,0,172,0,0,4,0,0,0,8.7,172,40.2,3,2017-08-12T14:00:00Z,12 Aug 15:00,0,0,90,0,1,6,0,0,0,0,5,0,1,0,59955,2,0,0,3,0,0.0,6,0,0,0,55,False,0,0,1

#### FPL 2018-19 Gameweek

In [163]:
folder_path = '../../data/raw/2018-19/gws'
combine_gameweeks(folder_path, 'combined_gws_1819')

In [164]:
df = pd.read_csv('../../data/processed/gameweek/combined_gws_1819.csv')

print(df.shape)
print(df.columns)

(21790, 56)
Index(['name', 'assists', 'attempted_passes', 'big_chances_created',
       'big_chances_missed', 'bonus', 'bps', 'clean_sheets',
       'clearances_blocks_interceptions', 'completed_passes', 'creativity',
       'dribbles', 'ea_index', 'element', 'errors_leading_to_goal',
       'errors_leading_to_goal_attempt', 'fixture', 'fouls', 'goals_conceded',
       'goals_scored', 'ict_index', 'id', 'influence', 'key_passes',
       'kickoff_time', 'kickoff_time_formatted', 'loaned_in', 'loaned_out',
       'minutes', 'offside', 'open_play_crosses', 'opponent_team', 'own_goals',
       'penalties_conceded', 'penalties_missed', 'penalties_saved',
       'recoveries', 'red_cards', 'round', 'saves', 'selected', 'tackled',
       'tackles', 'target_missed', 'team_a_score', 'team_h_score', 'threat',
       'total_points', 'transfers_balance', 'transfers_in', 'transfers_out',
       'value', 'was_home', 'winning_goals', 'yellow_cards', 'GW'],
      dtype='object')

In [165]:
df.head(3)

,name,assists,attempted_passes,big_chances_created,big_chances_missed,bonus,bps,clean_sheets,clearances_blocks_interceptions,completed_passes,creativity,dribbles,ea_index,element,errors_leading_to_goal,errors_leading_to_goal_attempt,fixture,fouls,goals_conceded,goals_scored,ict_index,id,influence,key_passes,kickoff_time,kickoff_time_formatted,loaned_in,loaned_out,minutes,offside,open_play_crosses,opponent_team,own_goals,penalties_conceded,penalties_missed,penalties_saved,recoveries,red_cards,round,saves,selected,tackled,tackles,target_missed,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,winning_goals,yellow_cards,GW
0,Aaron_Cresswell_402,0,0,0,0,0,0,0,0,0,0.0,0,0,402,0,0,5,0,0,0,0.0,402,0.0,0,2018-08-12T12:30:00Z,12 Aug 13:30,0,0,0,0,0,12,0,0,0,0,0,0,1,0,103396,0,0,0,0,4,0.0,0,0,0,0,55,False,0,0,1
1,Aaron_Lennon_83,0,22,0,1,0,6,1,1,17,12.3,0,0,83,0,0,8,1,0,0,3.9,83,10.0,0,2018-08-12T12:30:00Z,12 Aug 13:30,0,0,90,0,1,16,0,0,0,0,2,0,1,0,15138,1,2,0,0,0,17.0,3,0,0,0,50,False,0,0,1
2,Aaron_Mooy_199,0,51,0,0,0,24,0,2,40,18.2,1,0,199,0,0,4,1,3,0,3.8,199,20.2,1,2018-08-11T14:00:00Z,11 Aug 15:00,0,0,90,0,0,6,0,0,0,0,11,0,1,0,192110,1,6,0,3,0,0.0,2,0,0,0,55,True,0,0,1

#### FPL 2019-20 Gameweek

In [166]:
folder_path = '../../data/raw/2019-20/gws'
combine_gameweeks(folder_path, 'combined_gws_1920')

In [167]:
df = pd.read_csv('../../data/processed/gameweek/combined_gws_1920.csv')

print(df.shape)
print(df.columns)

(22560, 33)
Index(['name', 'assists', 'bonus', 'bps', 'clean_sheets', 'creativity',
       'element', 'fixture', 'goals_conceded', 'goals_scored', 'ict_index',
       'influence', 'kickoff_time', 'minutes', 'opponent_team', 'own_goals',
       'penalties_missed', 'penalties_saved', 'red_cards', 'round', 'saves',
       'selected', 'team_a_score', 'team_h_score', 'threat', 'total_points',
       'transfers_balance', 'transfers_in', 'transfers_out', 'value',
       'was_home', 'yellow_cards', 'GW'],
      dtype='object')

In [168]:
df

,name,assists,bonus,bps,clean_sheets,creativity,element,fixture,goals_conceded,goals_scored,ict_index,influence,kickoff_time,minutes,opponent_team,own_goals,penalties_missed,penalties_saved,red_cards,round,saves,selected,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
0,Aaron_Cresswell_376,0,0,7,0,1.5,376,8,5,0,1.1,9.0,2019-08-10T11:30:00Z,90,11,0,0,0,0,1,0,23399,5.0,0.0,0.0,0,0,0,0,50,True,0,1
1,Aaron_Lennon_430,0,0,3,0,0.0,430,3,0,0,0.2,2.0,2019-08-10T14:00:00Z,6,16,0,0,0,0,1,0,8105,0.0,3.0,0.0,1,0,0,0,50,True,0,1
2,Aaron_Mooy_516,0,0,0,0,0.0,516,7,0,0,0.0,0.0,2019-08-10T14:00:00Z,0,18,0,0,0,0,1,0,16261,3.0,0.0,0.0,0,0,0,0,50,False,0,1
3,Aaron_Ramsdale_494,0,0,11,0,0.0,494,2,1,0,1.0,9.8,2019-08-10T14:00:00Z,90,15,0,0,0,0,1,2,3091,1.0,1.0,0.0,2,0,0,0,45,True,0,1
4,Aaron_Wan-Bissaka_122,0,2,34,1,16.1,122,9,0,0,4.9,30.4,2019-08-11T15:30:00Z,90,6,0,0,0,0,1,0,1879259,0.0,4.0,2.0,8,0,0,0,55,True,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22555,Yoshinori_Muto_260,0,0,0,0,0.0,260,83,0,0,0.0,0.0,2019-10-19T14:00:00Z,0,6,0,0,0,0,9,0,7605,0.0,1.0,0.0,0,-289,200,489,53,False,0,9
22556,Youri_Tielemans_448,0,2,30,0,37.2,448,86,1,1,11.4,51.4,2019-10-19T14:00:00Z,90,5,0,0,0,0,9,0,284856,1.0,2.0,25.0,9,-7831,15015,22846,64,True,0,9
22557,Yves_Bissouma_53,0,0,0,0,0.0,53,81,0,0,0.0,0.0,2019-10-19T14:00:00Z,0,2,0,0,0,0,9,0,667,1.0,2.0,0.0,0,20,75,55,50,False,0,9
22558,Çaglar_Söyüncü_164,0,0,16,0,0.9,164,86,1,0,5.2,41.2,2019-10-19T14:00:00Z,90,5,0,0,0,0,9,0,522264,1.0,2.0,10.0,2,68502,84959,16457,47,True,0,9
22559,Ørjan_Nyland_27,0,0,0,0,0.0,27,81,0,0,0.0,0.0,2019-10-19T14:00:00Z,0,4,0,0,0,0,9,0,10701,1.0,2.0,0.0,0,-322,98,420,44,True,0,9

In [169]:
df.head(3)

,name,assists,bonus,bps,clean_sheets,creativity,element,fixture,goals_conceded,goals_scored,ict_index,influence,kickoff_time,minutes,opponent_team,own_goals,penalties_missed,penalties_saved,red_cards,round,saves,selected,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
0,Aaron_Cresswell_376,0,0,7,0,1.5,376,8,5,0,1.1,9.0,2019-08-10T11:30:00Z,90,11,0,0,0,0,1,0,23399,5.0,0.0,0.0,0,0,0,0,50,True,0,1
1,Aaron_Lennon_430,0,0,3,0,0.0,430,3,0,0,0.2,2.0,2019-08-10T14:00:00Z,6,16,0,0,0,0,1,0,8105,0.0,3.0,0.0,1,0,0,0,50,True,0,1
2,Aaron_Mooy_516,0,0,0,0,0.0,516,7,0,0,0.0,0.0,2019-08-10T14:00:00Z,0,18,0,0,0,0,1,0,16261,3.0,0.0,0.0,0,0,0,0,50,False,0,1

#### FPL 2020-21 Gameweek

In [170]:
folder_path = '../../data/raw/2020-21/gws'
combine_gameweeks(folder_path, 'combined_gws_2021')

In [171]:
df = pd.read_csv('../../data/processed/gameweek/combined_gws_2021.csv')

print(df.shape)
print(df.columns)

(24365, 36)
Index(['name', 'position', 'team', 'xP', 'assists', 'bonus', 'bps',
       'clean_sheets', 'creativity', 'element', 'fixture', 'goals_conceded',
       'goals_scored', 'ict_index', 'influence', 'kickoff_time', 'minutes',
       'opponent_team', 'own_goals', 'penalties_missed', 'penalties_saved',
       'red_cards', 'round', 'saves', 'selected', 'team_a_score',
       'team_h_score', 'threat', 'total_points', 'transfers_balance',
       'transfers_in', 'transfers_out', 'value', 'was_home', 'yellow_cards',
       'GW'],
      dtype='object')

In [172]:
df.head(3)

,name,position,team,xP,assists,bonus,bps,clean_sheets,creativity,element,fixture,goals_conceded,goals_scored,ict_index,influence,kickoff_time,minutes,opponent_team,own_goals,penalties_missed,penalties_saved,red_cards,round,saves,selected,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
0,Aaron Connolly,FWD,Brighton,0.5,0,0,-3,0,0.3,78,7,2,0,3.4,1.2,2020-09-14T19:15:00Z,45,5,0,0,0,0,1,0,32205,3,1,32.0,1,0,0,0,55,True,0,1
1,Aaron Cresswell,DEF,West Ham,2.1,0,0,11,0,11.2,435,6,2,0,2.2,10.4,2020-09-12T19:00:00Z,90,14,0,0,0,0,1,0,70232,2,0,0.0,1,0,0,0,50,True,0,1
2,Aaron Mooy,MID,Brighton,0.0,0,0,0,0,0.0,60,7,0,0,0.0,0.0,2020-09-14T19:15:00Z,0,5,0,0,0,0,1,0,2010,3,1,0.0,0,0,0,0,50,True,0,1

#### FPL 2021-22 Gameweek

In [173]:
folder_path = '../../data/raw/2021-22/gws'
combine_gameweeks(folder_path, 'combined_gws_2122')

In [174]:
df = pd.read_csv('../../data/processed/gameweek/combined_gws_2122.csv')

print(df.shape)
print(df.columns)

(25447, 36)
Index(['name', 'position', 'team', 'xP', 'assists', 'bonus', 'bps',
       'clean_sheets', 'creativity', 'element', 'fixture', 'goals_conceded',
       'goals_scored', 'ict_index', 'influence', 'kickoff_time', 'minutes',
       'opponent_team', 'own_goals', 'penalties_missed', 'penalties_saved',
       'red_cards', 'round', 'saves', 'selected', 'team_a_score',
       'team_h_score', 'threat', 'total_points', 'transfers_balance',
       'transfers_in', 'transfers_out', 'value', 'was_home', 'yellow_cards',
       'GW'],
      dtype='object')

In [175]:
df.head(3)

,name,position,team,xP,assists,bonus,bps,clean_sheets,creativity,element,fixture,goals_conceded,goals_scored,ict_index,influence,kickoff_time,minutes,opponent_team,own_goals,penalties_missed,penalties_saved,red_cards,round,saves,selected,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
0,Eric Bailly,DEF,Man Utd,0.0,0,0,0,0,0.0,286,6,0,0,0.0,0.0,2021-08-14T11:30:00Z,0,10,0,0,0,0,1,0,9363,1,5,0.0,0,0,0,0,50,True,0,1
1,Keinan Davis,FWD,Aston Villa,0.4,0,0,0,0,0.0,49,8,0,0,0.0,0.0,2021-08-14T14:00:00Z,0,18,0,0,0,0,1,0,169789,2,3,0.0,0,0,0,0,45,False,0,1
2,Ayotomiwa Dele-Bashiru,MID,Watford,0.0,0,0,0,0,0.0,394,8,0,0,0.0,0.0,2021-08-14T14:00:00Z,0,2,0,0,0,0,1,0,4092,2,3,0.0,0,0,0,0,45,True,0,1

#### FPL 2022-23 Gameweek

In [176]:
folder_path = '../../data/raw/2022-23/gws'
combine_gameweeks(folder_path, 'combined_gws_2223')

C:\Users\marse\AppData\Local\Temp\ipykernel_2256\648192233.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat(data_frames, ignore_index=True)

In [177]:
df = pd.read_csv('../../data/processed/gameweek/combined_gws_2223.csv')

print(df.shape)
print(df.columns)

(26505, 41)
Index(['name', 'position', 'team', 'xP', 'assists', 'bonus', 'bps',
       'clean_sheets', 'creativity', 'element', 'expected_assists',
       'expected_goal_involvements', 'expected_goals',
       'expected_goals_conceded', 'fixture', 'goals_conceded', 'goals_scored',
       'ict_index', 'influence', 'kickoff_time', 'minutes', 'opponent_team',
       'own_goals', 'penalties_missed', 'penalties_saved', 'red_cards',
       'round', 'saves', 'selected', 'starts', 'team_a_score', 'team_h_score',
       'threat', 'total_points', 'transfers_balance', 'transfers_in',
       'transfers_out', 'value', 'was_home', 'yellow_cards', 'GW'],
      dtype='object')

In [178]:
df.head(3)

,name,position,team,xP,assists,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,fixture,goals_conceded,goals_scored,ict_index,influence,kickoff_time,minutes,opponent_team,own_goals,penalties_missed,penalties_saved,red_cards,round,saves,selected,starts,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
0,Nathan Redmond,MID,Southampton,1.5,0,0,3,0,0.0,403,0.0,0.0,0.0,0.0,8,0,0,0.0,0.0,2022-08-06T14:00:00Z,1,18,0,0,0,0,1,0,5871,0,1,4,0.0,1,0,0,0,55,False,0,1
1,Junior Stanislas,MID,Bournemouth,1.1,0,0,3,0,0.0,58,0.0,0.0,0.0,0.0,2,0,0,0.0,0.0,2022-08-06T14:00:00Z,1,2,0,0,0,0,1,0,9491,0,0,2,0.0,1,0,0,0,50,True,0,1
2,Armando Broja,FWD,Chelsea,2.0,0,0,3,0,0.3,150,0.0,0.0,0.0,0.0,3,0,0,2.5,5.2,2022-08-06T16:30:00Z,15,8,0,0,0,0,1,0,124903,0,1,0,19.0,1,0,0,0,55,False,0,1

#### FPL 2023-24 Gameweek

In [179]:
folder_path = '../../data/raw/2023-24/gws'
combine_gameweeks(folder_path, 'combined_gws_2324')

In [180]:
df = pd.read_csv('../../data/processed/gameweek/combined_gws_2324.csv')

print(df.shape)
print(df.columns)

(29725, 41)
Index(['name', 'position', 'team', 'xP', 'assists', 'bonus', 'bps',
       'clean_sheets', 'creativity', 'element', 'expected_assists',
       'expected_goal_involvements', 'expected_goals',
       'expected_goals_conceded', 'fixture', 'goals_conceded', 'goals_scored',
       'ict_index', 'influence', 'kickoff_time', 'minutes', 'opponent_team',
       'own_goals', 'penalties_missed', 'penalties_saved', 'red_cards',
       'round', 'saves', 'selected', 'starts', 'team_a_score', 'team_h_score',
       'threat', 'total_points', 'transfers_balance', 'transfers_in',
       'transfers_out', 'value', 'was_home', 'yellow_cards', 'GW'],
      dtype='object')

In [181]:
df.head(3)

,name,position,team,xP,assists,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,fixture,goals_conceded,goals_scored,ict_index,influence,kickoff_time,minutes,opponent_team,own_goals,penalties_missed,penalties_saved,red_cards,round,saves,selected,starts,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
0,Femi Seriki,DEF,Sheffield Utd,0.5,0,0,0,0,0.0,653,0.00,0.00,0.0,0.00,7,0,0,0.0,0.0,2023-08-12T14:00:00Z,0,8,0,0,0,0,1,0,0,0,1,0,0.0,0,0,0,0,40,True,0,1
1,Jack Hinshelwood,MID,Brighton,1.5,0,0,0,0,0.0,621,0.00,0.00,0.0,0.00,4,0,0,0.0,0.0,2023-08-12T14:00:00Z,0,12,0,0,0,0,1,0,822,0,1,4,0.0,0,0,0,0,45,True,0,1
2,Jadon Sancho,MID,Man Utd,3.0,0,0,4,0,11.3,397,0.05,0.05,0.0,1.08,10,0,0,2.3,3.8,2023-08-14T19:00:00Z,22,20,0,0,0,0,1,0,83993,0,0,1,8.0,1,0,0,0,70,True,0,1